### ISSUE TITLE
Departure List - Fragezeichen

### ISSUE THREAD

**Issue by Bernd99** [jonaseberle/euroscope-afv-wine#13]
Hallo Jonas,

zunächst vielen Dank für die Anleitung und das Script. Ich habe das an meinem Mac (Mac Studio, OS 15.1 Beta) umgesetzt. Das hat soweit gut geklappt (für getopt musste ich zuvor noch einen Pfad setzen). EuroScope startet erfolgreich, Vatsim connect funktioniert  und TrackAudio geht auch gut. 

Folgende Fehler sind noch vorhanden:
a) IASsure meldet: Weather: Failed to load weather data
b) Fragezeichen in der Departure List (siehe beigefügten Screenshot)

Vielleicht hast Du eine Idee?

VG Bernd

![2024-10-19_19-03-08](https://github.com/user-attachments/assets/b96b0b4a-4dfc-4872-949c-3f3826e5c811)

**Comment by Bernd99** [comment]
Hallo Jonas,

inzwischen habe ich das Problem gelöst. Das Plugin TopSky wurde nicht geladen, weil das Visual C++ Redistributable Package nicht richtig installiert war. Das habe ich auch nicht geschafft; es fehlte der nötige installer in wine (windows). Letztlich habe ich es geschafft, Euroscope über Crossover (Lizenz hatte ich!) zu installieren.

Viele Grüße
Bernd

**Comment by jonaseberle** [comment]
Da fehlt ein Font in wine, den EuroScope da benutzt. Das ist aber irgendwas non-Standard, was auch der EuroScope-Installer nicht installiert. Evtl. kannst Du ihn nachinstallieren.
Tut mir leid, das sprengt etwas den Fokus dieses Scripts.
