### ISSUE TITLE
Problems with CCAMS plugin, solved with different winetricks verbs

### ISSUE THREAD

**Issue by fagidutt** [jonaseberle/euroscope-afv-wine#14]
After a lot of testing i was able to get EuroScope installed and working with all the plugins from our Sectorfile.
I installed only those two winetricks verbs: vcrun2010, vcrun2022 in the wineprefix i used to install ES in.
With the verbs from the install script, CCAMS plugin was missing information about some SSL cipher suite used for the server communication of the plugin, i'm not sure, however, if this is due to vcrun2010 or vcrun2022 missing.

I'm still conducting further testing, and will update this issue with further information if it comes up.

For reference: I'm running Linux Mint 22 with the Repo-Maintained version of Wine (currently 9.0).
If you need any further information do not hesitate to ask.

**Comment by jonaseberle** [comment]
We can't support all EuroScope plugins, but CCAMS is pretty widespread.

If you can figure out which is needed (vcrun2010 or vcrun2022) I would add that to the base install script.

**Comment by fagidutt** [comment]
I didn't test on a completely new prefix, but uninstalling vcrun2022 with 2010 present renders EuroScope unusable. On the other hand, removing 2010 didn't seem to result in any issues. Also, the installer for 2022 mentions it is for the runtimes 2015-2022, so i'd assume all those are included.

I also forgot to mention above that i'm running euroscope in a pure 32-bit WINEARCH prefix, so results may vary.

**Comment by fagidutt** [comment]
FYI: My wine version is 9.21. I just tested ES with a new, 64 bit prefix. I installed exclusively vcrun2022, no other verbs, and did not encounter issues while starting and plugin self-checks. Didn't test any further than that, yet, but will probably give it a try tonight.
