### ISSUE TITLE
Sha256sum mismatch for vcredist_x86

### ISSUE THREAD

**Issue by javoescan** [jonaseberle/euroscope-afv-wine#2]
## Expected Behavior
Installation should finish successfully

## Current Behavior
Installation breaks when trying to install vcredist_x86.exe

## Detailed Description
Cloned the repo, run the sh file and got the following error while installing
`sha256sum mismatch! Rename /home/javo/.cache/winetricks/vcrun2010/vcredist_x86.exe and try again.`
I have renamed the file but got the same output.

PS thank you for this, it's amazing indeed!

**Comment by jonaseberle** [comment]
Thank you. Yes, I noticed that as well in the [test runs](https://github.com/jonaseberle/euroscope-afv-wine/actions/workflows/test-install.yml).

Which `winetrick --version` do you have?. Could you try a `winetricks --self-update`? 
I am also adding that to the test runs to see if that fixes the problem.

**Comment by javoescan** [comment]
Sorry about that, forgot to add the version. I've run the self-update command and now I have `20210206-next`. With that version the script finishes succesfully, although AFV is crashing when it starts but I think you have already reported this in VATSIM's forum so I'm ok to close this issue.

**Comment by javoescan** [comment]
If it helps I'm getting `Unhandled Exception: System.Runtime.InteropServices.COMException: Exception from
 HRESULT: 0x8000FFFF (E_UNEXPECTED)` when starting AFV

**Comment by jonaseberle** [comment]
Yes, that's what I am seeing too unfortunately since a week :(
I have tried multiple wine versions with the help of https://lutris.net/ but can't get AfV working any more :(

https://lutris.net/ might be a way to provide a recipe that comes together with a wine version by the way. In the long run if we continue to have problems with a simple script this might be more viable.

**Comment by javoescan** [comment]
I managed to get it working a few weeks ago, I'll try to get that state back and let you know. Although AFV was starting, it wouldn't connect to VATSIM because of a network issue that I wasn't able to workaround. Let me know if you would like to continue this conversation offline!

**Comment by jonaseberle** [comment]
Thank you. I am on the Swift discord regularly. We could use voice there or I am happy to join you somewhere else. Or offline if you like of course, but I am in Stuttgart (Southern Germany) :)

**Comment by javoescan** [comment]
What is your discord username?

**Comment by jonaseberle** [comment]
flightwusel#6332 Swift discord: https://discord.gg/jUnSEM2U
