### ISSUE TITLE
./euroscope-afv-wine_install.sh: line 188: syntax error near unexpected token `>'

### ISSUE THREAD

**Issue by kaspis29** [jonaseberle/euroscope-afv-wine#4]
Receiving the above errror when trying to install Euroscope. Wine and required packages installed.

Also raises this:  /`euroscope-afv-wine_install.sh: line 151: /usr/local/bin/wine: Bad CPU type in executable`

System: macOS Monterey 12.1 (intel machine)

Note: error is most likely user side (on me)

**Comment by FValent3** [comment]
&>> is a syntax introduced in bash 4. I don´t know if this is supported by zsh (default mac shell)

The fix i found need to edit lines 188, 194, 200 in euroscope-afv-wine_install.sh

For example:

  "$wineBin" "$@" &>>"$logFilename"

to

  "$wineBin" "$@" >> "$logFilename" 2>&1

**Comment by jonaseberle** [comment]
Sorry, I seem to have missed the earlier notification about this issue.

While I believe that even in a `zsh` shell that script is run by `bash` (due to the `#!/bin/bash` "shebang") if that made problems let's fix it.

Thanks @FValent3 for finding the cause and pointing that out!
