### ISSUE TITLE
‹getopt --test› failed

### ISSUE THREAD

**Issue by jasbury22** [jonaseberle/euroscope-afv-wine#6]
Hello, during the installation I receive the following error.  I am running Mac Monterey 12.6.3.

Ts-iMac:wine [USER]$ ../euroscope-afv-wine_install.sh --help
‹getopt --test› failed in this environment.

What should I do?

**Comment by jonaseberle** [comment]
Hi,
we do this to test for a current version of `getopt`.
This is what I get:
```
$ getopt -V
getopt from util-linux 2.38.1
```
To be honest I don't know currently which version we need. 

You can try updating or try to remove this version check: 
https://github.com/jonaseberle/euroscope-afv-wine/blob/main/euroscope-afv-wine_install.sh#L58-L62

**Comment by daan33** [comment]
This (and issue #7) have to do with the fact that macOS uses BSD-based `getopt` instead of the GNU-based `getopt` commonly found on Linux. Use homebrew to install the `gnu-getopt` package (`brew install gnu-getopt`) and the problem will be solved!

**Comment by jonaseberle** [comment]
Thanks. So let's add that to the requirements.
