### ISSUE TITLE
Getopt Illegal Option

### ISSUE THREAD

**Issue by jacobtilly** [jonaseberle/euroscope-afv-wine#7]
Hi,
When I try to run the install script on MacOS, I get the following:

`> ../euroscope-afv-wine_install.sh --euroscope --no-euroscope-beta

getopt: illegal option -- l
getopt: illegal option -- g
getopt: illegal option -- ,
getopt: illegal option -- r
getopt: illegal option -- b
getopt: illegal option -- ,
getopt: illegal option -- u
getopt: illegal option -- r
getopt: illegal option -- c
getopt: illegal option -- ,
getopt: illegal option -- u
getopt: illegal option -- r
getopt: illegal option -- c
getopt: illegal option -- b
getopt: illegal option -- ,
getopt: illegal option -- f
getopt: illegal option -- ,
getopt: illegal option -- l
getopt: illegal option -- ,
getopt: illegal option -- c
getopt: illegal option -- c
getopt: illegal option -- d
getopt: illegal option -- m
Usage: euroscope-afv-wine_install.sh [<options>]
  <options>:
	-h|--help               this help
	-a|--afv                install only afv
	-e|--euroscope          install only EuroScope
	-B|--no-euroscope-beta  do not install latest EuroScope beta
	-y|--yes                no confirmations
	--cached                use cached versions of already downloaded files
	-v|--verbose            echo all script commands`

I tried running with --verbose, but the output was the same. 

Earlier, I got the `‹getopt --test› failed in this environment.` error. As per the reported issue, I tried removing the version check, and that was when I got the above instead.

**Comment by jonaseberle** [comment]
Please report your version in https://github.com/jonaseberle/euroscope-afv-wine/issues/6 as I have asked the other Mac user already, too.
